# possible verdicts

CORRECT_ANSWER = 'CORRECT_ANSWER'
WRONG_ANSWER = 'WRONG_ANSWER'
WRONG_COMPLEXITY = 'WRONG_COMPLEXITY'
RUNTIME_ERROR = 'RUNTIME_ERROR'
COMPILE_ERROR = 'COMPILE_ERROR'
IN_EXECUTION = 'IN_EXECUTION'
TIME_LIMIT_EXCEEDED = 'TIME_LIMIT_EXCEEDED'